version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marcel-expenses-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb+srv://malekurt53:c2W5wfGYQovils7v@attend-wise.w8wfxrd.mongodb.net/attend-wise?retryWrites=true&w=majority&appName=attend-wise
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 30d
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
      - ./backend/reports:/app/reports
    networks:
      - marcel-expenses-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marcel-expenses-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - marcel-expenses-network

networks:
  marcel-expenses-network:
    driver: bridge
